name: Run tests

on: [push,workflow_dispatch]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        compiler: [gcc, clang]

    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v4

      - name: Setup dependencies
        run: |
          sudo apt update
          sudo apt upgrade
          sudo apt-get install -y libcriterion-dev libopenblas-dev

      - name: Compile
        env:
          CC: ${{ matrix.compiler }}
        run: |
          cmake -DBUILD_TESTING=ON -DBUILD_OPENMP_TESTS=ON -S . -B /tmp/build
          cmake --build /tmp/build

      - name: Run tests
        run: |
          cd /tmp/build
          make vtest

