name: Run tests

on: [push,workflow_dispatch]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v4

      - name: Setup dependencies
        run: |
          sudo apt update
          sudo apt upgrade
          sudo apt-get install -y libcriterion-dev
          sudo apt-get install -y libopenblas-dev liblapack-dev

      - name: Run tests
        run: |
          mkdir bin
          mkdir build
          cd tests
          mkdid build
          make
          ../bin/unit_test -j1 --verbose=0
          make clean
